BOT_TOKEN = "BOT_TOKEN"
PAYMENTS_PROVIDER_TOKEN = "PAYMENT_TOKEN"

WEBHOOK_HOST = "NGROK_URL"
WEBHOOK_PATH = f"/webhook/{BOT_TOKEN}"
WEBHOOK_URL = f"{WEBHOOK_HOST}{WEBHOOK_PATH}"

WEBAPP_HOST = "localhost"
WEBAPP_PORT = 3001

ADMIN_LOGIN = "admin"
ADMIN_PASSWORD = "admin"

shopId = 506751
shopArticleId = 538350

ONE_UNIT = 100
CURRENCY = 'rub'
ERROR_PAYMENT_MESSAGE = "При оплате произошла ошибка"

SHOP_COMMAND = "shop"

ADMIN_CHAT_ID = 00000000

EMPTY_PHOTO_ID = "AgACAgIAAxkDAAPaYE6hZSfG-HOeXDhxM4bhEuSkXBgAAlGxMRtNDHhKGtZSOnS9hiRx3mGaLgADAQADAgADbQADRtMGAAEeBA"
